'use client'

import '@/toolbox/themes/sass/_index.sass'

import { getInitColorSchemeScript } from '@mui/material'
import { Montserrat_Alternates } from 'next/font/google'
import { ReactNode, } from 'react'

import { Layout } from '@/common/layout/Layout'
import { ThemeMuiContextProvider } from '@/context/ThemeMuiContext'
import { ETheme } from '@/toolbox/enums/Theme'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const font = Montserrat_Alternates({
  variable: '--font-montserrat_alternates',
  subsets: ['latin'],
  weight: ['400', '600', '700'],
})

export default function RootLayout({ children }: { children: ReactNode }) {

  return (
    <html lang='es'>
      <body className={font.className}>
        {getInitColorSchemeScript({ defaultMode:ETheme.SYSTEM })}
        <ThemeMuiContextProvider>
          <Layout>
            {children}
          </Layout>
        </ThemeMuiContextProvider>
      </body>
      {/* <Script defer src="https://app.embed.im/snow.js" /> */}
    </html>
  )
}
