export const RHome = '/'
export const RAbout = '/about'
export const RContact = '/contact'
export const RProyects = '/proyects'
export const RExperience = '/experience'
export const RRecommendations = '/recommendations'